### ISSUE TITLE
[FEATURE] Homework

### ISSUE THREAD

**Issue by Julius-Babies** [VPlanPlus-Project/VPlanPlus#279]
## To-Do
- [x] Fix sync
- [x] Firebase on server
- [x] Firebase on client
- [X] Notifications 8de094c7560329122a488e474082a0dd812995e1
- [X] Navigation fix 8c2247a7e1ea6565fbd2daa6104b995805012a24
- [x] Implement error messages when server didn't respond as expected 2b4a88bc19a819206871e7912e3b99addb7b717f
  - [x] Create homework
  - [x] Delete task
  - [x] Share/Unshare homework
  - [x] Delete homework
  - [x] Add task
  - [x] Change task content
  - [x] Change task state
- [X] Show loading state a521679749b1d1ae738ed107ad6700f2c66b56ba
  - [x] Add homework
  - [x] Mark homework as done
  - [x] Change task state
  - [x] Change task content
  - [x] Delete task
  - [x] Delete homework
  - [x] Share homework
- [x] Pull to refresh gesture 0bc38ed6b76e08bf9d210ea3a1d2df1744fc1e34

**Comment by Julius-Babies** [comment]
- [ ] Fix sync
- [ ] Firebase on server
- [ ] Firebase on client
