### ISSUE TITLE
[FEATURE] Get notified for homework

### ISSUE THREAD

**Issue by Julius-Babies** [VPlanPlus-Project/VPlanPlus#356]
## ToDo
- [x] Avoid notifications for expired homework 3a0289dd3556d23c189731323adb287beae8204d
- [x] Avoid notifications on initial sync 3a0289dd3556d23c189731323adb287beae8204d
- [x] HomeworkSettings
  - [x] Send notification on new homework?
  - [x] Preferred notification times
- [x] DeepLink to homework
