### ISSUE TITLE
[TASK] Add Homework improvements

### ISSUE THREAD

**Issue by Julius-Babies** [VPlanPlus-Project/VPlanPlus#445]
> [!NOTE]
> These fields are optional

## Where?
AddHomeworkScreen
## Subtasks
- [x] Show weekday in Date Chips 3ea8a67ef19ce415d64e7a88e216070f64d4d3ef
- [ ] Allow null as DefaultLesson
  - [x] In Database and Processing 594fd4e018811a1f34dfeaf920ad21f75e2ca76c
  - [ ] UI
