### ISSUE TITLE
[TASK] New Homework view

### ISSUE THREAD

**Issue by Julius-Babies** [VPlanPlus-Project/VPlanPlus#543]
## Subtasks
- [x] Banner as tooltip
- [x] Add Homework as Sheet
- [x] Update Repository to match API
- [x] Clean architecture improvements
- [x] Sync fix
- [x] Detail Screen
  - [x] Change Visibility
  - [x] Improve visibility of pending updates
  - [x] smoothen animations
  - [x] optimize image performance
  - [x] Copy files with their name and extension when opened
- [x] Fix keyboard bouncing when balloons are visible
- [x] Use vpp.ID by default
- [x] List Screen (see Figma Designs)
  - [x] Add homework button
  - [x] Filters
  - [x] Group by date
  - [x] Fade Swipeable background / Round Corners to hide colour change
  - [x] Placeholder when none are visible
  - [x] Pull to refresh
  - [x] Balloon on first hide and snackbar to undo it
  - [x] Ballon for swiping
  - [X] ~Advertise homework reminders~
  - [x] Improve date headings
  - [X] ~Undo task done~
- [ ] #555
- [x] Add Placeholder if homework is disabled with button to enable it

**Comment by Julius-Babies** [comment]
Hope everything works for now, will be tested on internal channel
